function export_eeglab( params, filename )

load('example_eeg.mat');

%chans = params.channels;

EEG.setname = filename;
EEG.data = params.data;
EEG.points = size(EEG.data,2);

%for k=1:length(chans)
%    EEG.chanlocs(k) = get_chan( chans{k} );
%end
EEG.srate = params.srate;

pop_writebva(EEG, ['exports/' filename]);

end


function chann = get_chan(label)

chann = struct( ...
    'labels', label, ...
    'ref', '', ...
    'theta', [], ...
    'radius', [], ...
    'X', [], ...
    'Y', [], ...
    'Z', [], ...
    'sph_theta', [], ...
    'sph_phi', [], ...
    'sph_radius', [], ...
    'type', '', ...
    'urchan', [] ...
    );
end